### ISSUE TITLE
Homes

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [xXNiceYT/EssentialsCore#3]
/home {home name}
/sethome {home name}

/addhome {player} {amount of homes}

it would be like you can set an amount of homes a player can do and the default amount of homes
and the addhome cmd is for buycraft when people want to buy homes :)

**Comment by XoticRealmsOwnerandDev** [comment]
also make /fly take no damage and when hit you will be kicked out of fly but take no damage

**Comment by XoticRealmsOwnerandDev** [comment]
in plugin.yml add the perms to make it easyer for people to find permission nodes

**Comment by xXNiceAssasinl0** [comment]
I cannot add fly no damage

**Comment by XoticRealmsOwnerandDev** [comment]
also add /nick 
/unnick
/realname (player ign)
